version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS:-5050}
    ports:
      - "${ASPNETCORE_HTTP_PORTS:-5050}:${ASPNETCORE_HTTP_PORTS:-5050}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - ambev.developerevaluation.database
    command: ["sh", "-c", "until pg_isready -h ambev_developer_evaluation_database -p 5432; do echo waiting for db; sleep 2; done; dotnet Ambev.DeveloperEvaluation.WebApi.dll"]
    networks:
      - ambev_network

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/script-database.sql:/docker-entrypoint-initdb.d/script-database.sql
       
    networks:
      - ambev_network

volumes:   
     postgres:

networks:
  ambev_network:
    driver: bridge
